variants: fix EAFNOSUPPORT by updating reqwest
> Error: Error(Hyper(Error(Connect, Os { code: 97, kind: Uncategorized
> , message: "Address family not supported by protocol" })), "https://
> man.openbsd.org/OpenBSD-5.9/pledge.2")

This requires increasing the variants package MSRV from 1.36 to 1.56
(due to some dependencies requiring Rust 2021), which in turn requires
detaching it from the workspace (due to the root Cargo.lock needing to
stay in version 1 format), but the variants package is for maintainer
use anyway, so this is not a big deal.